### PR TITLE
Add optional behavior to ensure empty rows are emitted even when not present in the xlsx file.

### PR DESCRIPTION
**Pull request by continuousjr**
When a row is completely empty in excel with no data and no other meta information (cell formatting, etc), there is no <row /> tag in the XML representation, causing the missing row to be ignored by the sax parser, and therefore, by the Transformer even when the **ignoreEmpty** property is set to false.  This PR adds an additional option, **addMissingRows**, which, when **ignoreEmpty**  is falsey, will detect these missing rows and emit objects for these rows from the Transformer.

Missing rows are detected by observing gaps in the "r" attribute of the <row/> tag.  For example:
` 
<row r="1" spans="1:2" x14ac:dyDescent="0.2">...</row>
<row r="5" spans="1:2" x14ac:dyDescent="0.2">...</row>
`
means that rows 2,3, and 4 are empty.

Note, this functionality was added as optional, with a new option in order to preserve backwards compatibility with the prior behavior.

### CODE REVIEW

**Comment by jansivans** [comment]
Hi!
Thank you for PR.
I think we don't need a new property here. It is a bug if some rows are not emitted when `ignoreEmpty` option is set to `false`. And this bug can be fixed by your implementation.
If you agree with me, I would be very grateful if you could make some changes so `ignoreEmpty` would behave correctly, without additional options.

**Comment by continuousjr** [comment]
Sure thing.  The addMissingRows option has been removed.  Thanks!

**Review by jansivans — COMMENTED** [review]
Can you fix indentation problems inside `index.ts` file?
Otherwise it is hard to see what was changed.

**Comment by continuousjr** [comment]
Done.  Hope you don't mind I left a few CRs around function declarations for readability.

**Review by jansivans — APPROVED** [review]
Great work! Thank you!

**Pull request merged**
