### PR TITLE
Add skiprows option

### PR DESCRIPTION
**Pull request by TomNes94**
Added skiprows logic and types.

### CODE REVIEW

**Comment by jansivans** [comment]
Thanks for your PR.
It would be great if you can describe what is the use-case of this feature.

**Comment by TomNes94** [comment]
I encountered a problem with an Excel file where one of the first rows had a different column layout compared to the following rows. Skipping such a row evades the error thrown when the value of cell is assigned to _value_ :

`let value = ch.children.v.value;`

While ch.children exists, ch.children does not. Skipping rows helps circumvent the problem.

**Comment by jansivans** [comment]
Can you please share a file with this issue?

**Comment by TomNes94** [comment]
I cant share the Excel file because the data is private, but the issue is that the problematic row consists of merged cells.

**Comment by jansivans** [comment]
Can you make a custom file which reproduces this issue then?
Merged cells work fine for me.

**Comment by jansivans** [comment]
Closed for now due to inactivity.

**Pull request closed without merging**
